"""Non-tech variant — model + DAO.

Non-tech (AI/ML test-style) tasks also share the ``tasks`` table but:
  - ``task_blob.task_overview`` replaces ``short_overview``
  - ``task_blob.hints`` / ``task_blob.outcomes`` may be ``None``
  - ``task_blob.definitions`` may be an empty dict
  - top-level ``answer`` may be ``None`` (no canonical answer)
  - top-level ``solutions`` and ``readme_content`` are ``None``
    (no answer repo / no README)
  - ``eval_info`` only carries ``task_eval`` (no ``code_eval``)
  - ``task_id`` is pre-generated by the flow and included in the payload
"""
from __future__ import annotations

from typing import ClassVar, Dict, List, Optional, Type, Union

from pydantic import BaseModel, field_validator, model_validator

from task_validation.base import BaseTaskDAO, CriteriaEntry


class NonTechTaskBlob(BaseModel):
    model_config = {"strict": True}

    title: str
    definitions: Dict
    hints: Optional[str] = None
    resources: Dict
    outcomes: Optional[Union[str, List[str]]] = None
    question: str
    task_overview: List[str]

    @field_validator("title", "question")
    @classmethod
    def not_empty(cls, v: str) -> str:
        if not v or not v.strip():
            raise ValueError("must not be empty")
        return v

    @field_validator("task_overview")
    @classmethod
    def task_overview_strict_list(cls, v: List[str]) -> List[str]:
        if not isinstance(v, list):
            raise ValueError("must be a list of strings, not a string")
        if not v:
            raise ValueError("must not be an empty list")
        for item in v:
            if not isinstance(item, str) or not item.strip():
                raise ValueError("every entry must be a non-empty string")
        return v


class NonTechTaskForDB(BaseModel):
    model_config = {"strict": True}

    task_id: Optional[str] = None
    created_at: str
    pre_requisites: List[str]
    answer: Optional[str] = None
    criterias: List[CriteriaEntry]
    is_deployed: bool
    task_blob: NonTechTaskBlob
    is_shared_infra_required: bool
    readme_content: Optional[Dict] = None
    eval_info: Dict
    solutions: Optional[Dict] = None

    @field_validator("created_at")
    @classmethod
    def created_at_not_empty(cls, v: str) -> str:
        if not v or not v.strip():
            raise ValueError("must not be empty")
        return v

    @field_validator("criterias")
    @classmethod
    def criterias_not_empty(cls, v: List[CriteriaEntry]) -> List[CriteriaEntry]:
        if not v:
            raise ValueError("must contain at least one entry")
        return v

    @field_validator("pre_requisites")
    @classmethod
    def pre_requisites_strict_list(cls, v: List[str]) -> List[str]:
        if not isinstance(v, list):
            raise ValueError("must be a list of strings, not a string")
        if not v:
            raise ValueError("must not be an empty list")
        for item in v:
            if not isinstance(item, str) or not item.strip():
                raise ValueError("every entry must be a non-empty string")
        return v

    @field_validator("eval_info")
    @classmethod
    def eval_info_has_task_eval(cls, v: Dict) -> Dict:
        if "task_eval" not in v:
            raise ValueError("must contain 'task_eval' key")
        return v

    @field_validator("is_deployed")
    @classmethod
    def must_be_false_at_insert(cls, v: bool) -> bool:
        if v is not False:
            raise ValueError("must be False at insert time")
        return v

    @model_validator(mode="after")
    def no_duplicate_competency_ids(self) -> "NonTechTaskForDB":
        ids = [c.competency_id for c in self.criterias]
        seen, dupes = set(), set()
        for cid in ids:
            if cid in seen:
                dupes.add(cid)
            seen.add(cid)
        if dupes:
            raise ValueError(
                f"criterias contains duplicate competency_id values: {sorted(dupes)}"
            )
        return self


class NonTechTaskDAO(BaseTaskDAO):
    """DAO for non-tech (AI/ML test-style) tasks. Inherits FK check + insert from BaseTaskDAO."""

    MODEL: ClassVar[Type[BaseModel]] = NonTechTaskForDB
