"""
Input-files reader for the prompt-generator agent.

Loads three calibration signals from ``task_input_files/``:
  - ``questions_prompt``  — hand-curated sub-skill checklist (bullets)
  - ``role_context``      — 3-4 sentences on candidate responsibilities + YoE
  - existing scenarios    — 3-5 real Current/Your-Task/Success-Criteria blocks

These exist already (generated by ``generate_input_files/`` and
``scenario_generator/``) and are consumed by ``multiagent.py`` at runtime to
fill the ``{role_context}`` / ``{real_world_task_scenarios}`` /
``{question_prompt}`` placeholders inside the prompt templates this package
generates.

This module makes the same data available to ``prompt_generator/agent.py`` so
the *template language itself* can be calibrated against what's known to work.

Graceful degradation: every loader returns an empty string / empty list when
its source file is missing. Brand-new combos with no input files just fall
back to the seven-input agent path.
"""

from __future__ import annotations

import json
import logging
import re
from pathlib import Path

from prompt_generator.classifier import Competency

logger = logging.getLogger("prompt_generator")

REPO_ROOT = Path(__file__).parent.parent
INPUT_FILES_ROOT = REPO_ROOT / "task_input_files"
SCENARIOS_ROOT = INPUT_FILES_ROOT / "task_scenarios"

# Cap configuration — keep ``detailed_skill_signal`` under ~2K tokens.
MAX_QUESTIONS_BULLETS = 30
MAX_SCENARIOS = 3
QUESTIONS_HARD_CHAR_CAP = 4000
ROLE_CONTEXT_HARD_CHAR_CAP = 1200
SCENARIO_HARD_CHAR_CAP = 1200


def _slugify(name: str) -> str:
    """Mirror of the slug logic in ``__main__.py`` / ``retriever.py``."""
    s = name.lower()
    s = re.sub(r"\.js\b", "js", s)
    s = re.sub(r"\s*[-/&]\s*", "_", s)
    s = re.sub(r"[\s.]+", "_", s)
    s = re.sub(r"[^a-z0-9_]", "", s)
    s = re.sub(r"_+", "_", s).strip("_")
    return s


def _combo_slug(competency_names: list[str]) -> str:
    """Build the combined slug used in ``input_<slug>/`` directory names."""
    return "_".join(_slugify(n) for n in competency_names)


def _level_lower(proficiency: str) -> str:
    return proficiency.lower()


def _find_background_file(combo_slug: str, proficiency: str) -> Path | None:
    """Find the background_*.json file for this (combo, level).

    Folder layouts vary across combos — some have ``input_<slug>/<level>/<task>/``,
    others ``input_<slug>_<level>_task/`` flat. Glob recursively to be robust.
    """
    logger.debug("input_files: looking for background file slug=%r level=%s "
                 "under %s", combo_slug, proficiency, INPUT_FILES_ROOT)
    if not INPUT_FILES_ROOT.exists():
        logger.debug("input_files: INPUT_FILES_ROOT does not exist")
        return None
    level = _level_lower(proficiency)

    candidates: list[Path] = []
    parents_seen = 0
    for parent in INPUT_FILES_ROOT.glob(f"input_{combo_slug}*"):
        if not parent.is_dir():
            continue
        parents_seen += 1
        logger.debug("input_files: scanning %s", parent.name)
        for path in parent.rglob("background_*.json"):
            fname = path.name.lower()
            if level in fname:
                logger.debug("input_files:   candidate %s", path.name)
                candidates.append(path)
            else:
                logger.debug("input_files:   skip %s (no level=%s in filename)",
                             path.name, level)

    logger.debug("input_files: parents matching glob=%d, candidates=%d",
                 parents_seen, len(candidates))
    if not candidates:
        logger.debug("input_files: NO background file found for %r at %s",
                     combo_slug, proficiency)
        return None

    slug_tokens = set(combo_slug.split("_"))

    def score(p: Path) -> tuple[int, int]:
        fname = p.name.lower()
        matched = sum(1 for tok in slug_tokens if tok in fname)
        return (matched, -len(str(p)))

    candidates.sort(key=score, reverse=True)
    logger.debug("input_files: picked %s (best slug-token overlap)",
                 candidates[0].name)
    return candidates[0]


def load_background(combo_slug: str, proficiency: str) -> dict | None:
    """Load the background JSON for this (combo, level), or None if missing."""
    path = _find_background_file(combo_slug, proficiency)
    if not path:
        return None
    try:
        with path.open(encoding="utf-8") as f:
            return json.load(f)
    except (OSError, json.JSONDecodeError):
        return None


def load_role_context(combo_slug: str, proficiency: str) -> str:
    """Return the candidate role_context string, or '' if not available."""
    bg = load_background(combo_slug, proficiency)
    if not bg:
        return ""
    role = (bg.get("role_context") or "").strip()
    if len(role) > ROLE_CONTEXT_HARD_CHAR_CAP:
        role = role[:ROLE_CONTEXT_HARD_CHAR_CAP].rstrip() + "..."
    return role


def load_questions_prompt(combo_slug: str, proficiency: str) -> str:
    """Return the questions_prompt sub-skill checklist, truncated to top bullets."""
    bg = load_background(combo_slug, proficiency)
    if not bg:
        return ""
    raw = (bg.get("questions_prompt") or "").strip()
    if not raw:
        return ""
    return _truncate_bullets(raw, MAX_QUESTIONS_BULLETS, QUESTIONS_HARD_CHAR_CAP)


def _truncate_bullets(text: str, max_bullets: int, hard_char_cap: int) -> str:
    """Keep the lead paragraph + top-N bullet lines; cap total chars."""
    lines = text.splitlines()
    out: list[str] = []
    bullets_seen = 0
    for line in lines:
        stripped = line.lstrip()
        is_bullet = stripped.startswith(("-", "*", "•"))
        if is_bullet:
            if bullets_seen >= max_bullets:
                continue
            bullets_seen += 1
        out.append(line)
        if sum(len(l) + 1 for l in out) >= hard_char_cap:
            out.append("... [truncated]")
            break
    return "\n".join(out).strip()


def _scenario_key(competencies: list[Competency]) -> str:
    """Build the alpha-sorted '<Name> (<LEVEL>), <Name> (<LEVEL>)' key."""
    parts = sorted(
        f"{c.name} ({c.proficiency.upper()})" for c in competencies
    )
    return ", ".join(parts)


def _load_scenarios_index(proficiency: str) -> dict:
    """Load and merge the scenarios index files for this proficiency."""
    if not SCENARIOS_ROOT.exists():
        logger.debug("input_files: SCENARIOS_ROOT does not exist: %s", SCENARIOS_ROOT)
        return {}
    merged: dict = {}
    level = proficiency.upper()
    candidates = ["task_scenarios.json"]
    if level == "INTERMEDIATE":
        candidates.append("task_scenarios_intermediate.json")
    for fname in candidates:
        path = SCENARIOS_ROOT / fname
        if not path.exists():
            logger.debug("input_files: scenarios file missing: %s", path.name)
            continue
        try:
            with path.open(encoding="utf-8") as f:
                data = json.load(f)
            if isinstance(data, dict):
                merged.update(data)
                logger.debug("input_files: loaded %s with %d combo keys",
                             fname, len(data))
        except (OSError, json.JSONDecodeError) as e:
            logger.debug("input_files: failed to load %s: %s", fname, e)
    return merged


def load_scenarios_for_combo(
    competencies: list[Competency],
    max_scenarios: int = MAX_SCENARIOS,
) -> list[str]:
    """Return up to ``max_scenarios`` real scenarios for this combo, or [] if none."""
    index = _load_scenarios_index(competencies[0].proficiency if competencies else "BASIC")
    if not index:
        return []
    key = _scenario_key(competencies)
    raw = index.get(key, [])
    logger.debug("input_files: scenario lookup key=%r → %d raw entries",
                 key, len(raw) if isinstance(raw, list) else 0)
    if not isinstance(raw, list):
        return []
    scenarios: list[str] = []
    for item in raw[:max_scenarios]:
        text = item if isinstance(item, str) else str(item)
        text = text.strip()
        if len(text) > SCENARIO_HARD_CHAR_CAP:
            text = text[:SCENARIO_HARD_CHAR_CAP].rstrip() + "..."
        scenarios.append(text)
    return scenarios


def build_detailed_skill_signal(
    competencies: list[Competency],
    proficiency: str,
) -> tuple[str, dict]:
    """Build the bundled ``detailed_skill_signal`` string for the agent.

    Returns ``(signal_text, metadata_dict)``. The metadata is for the CLI banner
    (so users can see whether input files were found).
    """
    comp_names = [c.name for c in competencies]
    slug = _combo_slug(comp_names)

    questions = load_questions_prompt(slug, proficiency)
    role = load_role_context(slug, proficiency)
    scenarios = load_scenarios_for_combo(competencies)

    parts: list[str] = []
    if questions:
        parts.append(f"=== SUB-SKILL CHECKLIST ===\n{questions}")
    if role:
        parts.append(f"=== ROLE CONTEXT ===\n{role}")
    if scenarios:
        joined = "\n\n---\n\n".join(scenarios)
        parts.append(f"=== EXAMPLE SCENARIOS ({len(scenarios)}) ===\n{joined}")

    signal = "\n\n".join(parts)

    metadata = {
        "background_found": bool(questions or role),
        "questions_chars": len(questions),
        "role_context_chars": len(role),
        "scenarios_count": len(scenarios),
        "signal_chars": len(signal),
    }
    return signal, metadata
