"""
Input-files reader for the prompt-generator agent.

Loads three calibration signals from ``task_input_files/``:
  - ``questions_prompt``  — hand-curated sub-skill checklist (bullets)
  - ``role_context``      — 3-4 sentences on candidate responsibilities + YoE
  - existing scenarios    — 3-5 real Current/Your-Task/Success-Criteria blocks

These exist already (generated by ``generate_input_files/`` and
``scenario_generator/``) and are consumed by ``multiagent.py`` at runtime to
fill the ``{role_context}`` / ``{real_world_task_scenarios}`` /
``{question_prompt}`` placeholders inside the prompt templates this package
generates.

This module makes the same data available to ``prompt_generator/agent.py`` so
the *template language itself* can be calibrated against what's known to work.

Graceful degradation: every loader returns an empty string / empty list when
its source file is missing. Brand-new combos with no input files just fall
back to the seven-input agent path.
"""

from __future__ import annotations

import json
import logging
from pathlib import Path

from prompt_generator.classifier import Competency
from prompt_generator.slugs import competency_tokens, name_tokens, slugify

logger = logging.getLogger("prompt_generator")

REPO_ROOT = Path(__file__).parent.parent
INPUT_FILES_ROOT = REPO_ROOT / "task_input_files"
SCENARIOS_ROOT = INPUT_FILES_ROOT / "task_scenarios"

# Cap configuration — keep ``detailed_skill_signal`` under ~2K tokens.
MAX_QUESTIONS_BULLETS = 30
MAX_SCENARIOS = 3
QUESTIONS_HARD_CHAR_CAP = 4000
ROLE_CONTEXT_HARD_CHAR_CAP = 1200
SCENARIO_HARD_CHAR_CAP = 1200


def _combo_slug(competency_names: list[str]) -> str:
    """Build the combined slug used in ``input_<slug>/`` directory names.

    Kept for logging / metadata only — directory matching now goes through
    token-based scoring (see :func:`_find_background_file`), so the exact
    composite slug no longer needs to align with the on-disk folder name.
    """
    return "_".join(slugify(n) for n in competency_names)


def _level_lower(proficiency: str) -> str:
    return proficiency.lower()


def _find_background_file(
    competency_names: list[str],
    proficiency: str,
) -> Path | None:
    """Find background_*.json by token-matching competencies against directory names.

    Replaces the old strict ``input_{combo_slug}*`` glob, which assumed every
    on-disk folder followed the same naming convention as the slug builder
    (it doesn't — some folders use ``node``/others ``nodejs``,
    ``react``/``reactjs``/``react_framework``, and word order varies).

    Strategy: enumerate every ``input_*/`` directory, score each by how many
    competencies have at least one alias-aware token in the directory name, and
    require ALL competencies to match before considering the folder. Among
    matches, prefer folders whose name also contains the proficiency level.
    """
    logger.debug(
        "input_files: looking for background file for %r at %s under %s",
        competency_names, proficiency, INPUT_FILES_ROOT,
    )
    if not INPUT_FILES_ROOT.exists():
        logger.debug("input_files: INPUT_FILES_ROOT does not exist")
        return None
    level = _level_lower(proficiency)
    comp_token_sets = [competency_tokens(n) for n in competency_names]
    if not comp_token_sets:
        return None

    # (comp_matches, level_in_dirname, level_in_filename, -path_len) — higher is better.
    scored: list[tuple[tuple[int, int, int, int], Path]] = []
    parents_seen = 0
    for parent in INPUT_FILES_ROOT.glob("input_*"):
        if not parent.is_dir():
            continue
        parents_seen += 1
        dir_tokens = name_tokens(parent.name)
        comp_matches = sum(1 for tset in comp_token_sets if tset & dir_tokens)
        if comp_matches < len(comp_token_sets):
            logger.debug(
                "input_files: skip %s — only %d/%d competencies matched in dir tokens",
                parent.name, comp_matches, len(comp_token_sets),
            )
            continue
        level_in_dirname = 1 if level in dir_tokens else 0
        for path in parent.rglob("background_*.json"):
            fname_lower = path.name.lower()
            level_in_filename = 1 if level in fname_lower else 0
            # Require the level to appear somewhere — filename, dir, or
            # subpath — otherwise we'd cross-pollute Basic with Intermediate.
            subpath_has_level = (
                level_in_filename
                or level_in_dirname
                or any(level in name_tokens(p) for p in path.relative_to(parent).parts[:-1])
            )
            if not subpath_has_level:
                logger.debug(
                    "input_files:   skip %s (no level=%s anywhere on path)",
                    path.name, level,
                )
                continue
            score = (comp_matches, level_in_dirname, level_in_filename, -len(str(path)))
            scored.append((score, path))
            logger.debug(
                "input_files:   candidate %s  score=%s", path.name, score,
            )

    logger.debug(
        "input_files: parents scanned=%d, candidates=%d", parents_seen, len(scored),
    )
    if not scored:
        logger.debug(
            "input_files: NO background file found for %r at %s",
            competency_names, proficiency,
        )
        return None
    scored.sort(key=lambda t: t[0], reverse=True)
    picked = scored[0][1]
    logger.debug("input_files: picked %s (best score=%s)", picked.name, scored[0][0])
    return picked


def load_background(
    competency_names: list[str], proficiency: str,
) -> dict | None:
    """Load the background JSON for this (combo, level), or None if missing."""
    path = _find_background_file(competency_names, proficiency)
    if not path:
        return None
    try:
        with path.open(encoding="utf-8") as f:
            return json.load(f)
    except (OSError, json.JSONDecodeError):
        return None


def load_role_context(
    competency_names: list[str], proficiency: str,
) -> str:
    """Return the candidate role_context string, or '' if not available."""
    bg = load_background(competency_names, proficiency)
    if not bg:
        return ""
    role = (bg.get("role_context") or "").strip()
    if len(role) > ROLE_CONTEXT_HARD_CHAR_CAP:
        role = role[:ROLE_CONTEXT_HARD_CHAR_CAP].rstrip() + "..."
    return role


def load_questions_prompt(
    competency_names: list[str], proficiency: str,
) -> str:
    """Return the questions_prompt sub-skill checklist, truncated to top bullets."""
    bg = load_background(competency_names, proficiency)
    if not bg:
        return ""
    raw = (bg.get("questions_prompt") or "").strip()
    if not raw:
        return ""
    return _truncate_bullets(raw, MAX_QUESTIONS_BULLETS, QUESTIONS_HARD_CHAR_CAP)


def _truncate_bullets(text: str, max_bullets: int, hard_char_cap: int) -> str:
    """Keep the lead paragraph + top-N bullet lines; cap total chars."""
    lines = text.splitlines()
    out: list[str] = []
    bullets_seen = 0
    for line in lines:
        stripped = line.lstrip()
        is_bullet = stripped.startswith(("-", "*", "•"))
        if is_bullet:
            if bullets_seen >= max_bullets:
                continue
            bullets_seen += 1
        out.append(line)
        if sum(len(l) + 1 for l in out) >= hard_char_cap:
            out.append("... [truncated]")
            break
    return "\n".join(out).strip()


def _scenario_key(competencies: list[Competency]) -> str:
    """Build the alpha-sorted '<Name> (<LEVEL>), <Name> (<LEVEL>)' key."""
    parts = sorted(
        f"{c.name} ({c.proficiency.upper()})" for c in competencies
    )
    return ", ".join(parts)


def _load_scenarios_index(proficiency: str) -> dict:
    """Load and merge the scenarios index files for this proficiency."""
    if not SCENARIOS_ROOT.exists():
        logger.debug("input_files: SCENARIOS_ROOT does not exist: %s", SCENARIOS_ROOT)
        return {}
    merged: dict = {}
    level = proficiency.upper()
    candidates = ["task_scenarios.json"]
    if level == "INTERMEDIATE":
        candidates.append("task_scenarios_intermediate.json")
    for fname in candidates:
        path = SCENARIOS_ROOT / fname
        if not path.exists():
            logger.debug("input_files: scenarios file missing: %s", path.name)
            continue
        try:
            with path.open(encoding="utf-8") as f:
                data = json.load(f)
            if isinstance(data, dict):
                merged.update(data)
                logger.debug("input_files: loaded %s with %d combo keys",
                             fname, len(data))
        except (OSError, json.JSONDecodeError) as e:
            logger.debug("input_files: failed to load %s: %s", fname, e)
    return merged


def load_scenarios_for_combo(
    competencies: list[Competency],
    max_scenarios: int = MAX_SCENARIOS,
) -> list[str]:
    """Return up to ``max_scenarios`` real scenarios for this combo, or [] if none."""
    index = _load_scenarios_index(competencies[0].proficiency if competencies else "BASIC")
    if not index:
        return []
    key = _scenario_key(competencies)
    raw = index.get(key, [])
    logger.debug("input_files: scenario lookup key=%r → %d raw entries",
                 key, len(raw) if isinstance(raw, list) else 0)
    if not isinstance(raw, list):
        return []
    scenarios: list[str] = []
    for item in raw[:max_scenarios]:
        text = item if isinstance(item, str) else str(item)
        text = text.strip()
        if len(text) > SCENARIO_HARD_CHAR_CAP:
            text = text[:SCENARIO_HARD_CHAR_CAP].rstrip() + "..."
        scenarios.append(text)
    return scenarios


def build_detailed_skill_signal(
    competencies: list[Competency],
    proficiency: str,
) -> tuple[str, dict]:
    """Build the bundled ``detailed_skill_signal`` string for the agent.

    Returns ``(signal_text, metadata_dict)``. The metadata is for the CLI banner
    (so users can see whether input files were found).
    """
    comp_names = [c.name for c in competencies]

    questions = load_questions_prompt(comp_names, proficiency)
    role = load_role_context(comp_names, proficiency)
    scenarios = load_scenarios_for_combo(competencies)

    parts: list[str] = []
    if questions:
        parts.append(f"=== SUB-SKILL CHECKLIST ===\n{questions}")
    if role:
        parts.append(f"=== ROLE CONTEXT ===\n{role}")
    if scenarios:
        joined = "\n\n---\n\n".join(scenarios)
        parts.append(f"=== EXAMPLE SCENARIOS ({len(scenarios)}) ===\n{joined}")

    signal = "\n\n".join(parts)

    metadata = {
        "background_found": bool(questions or role),
        "questions_chars": len(questions),
        "role_context_chars": len(role),
        "scenarios_count": len(scenarios),
        "signal_chars": len(signal),
    }
    return signal, metadata
