"""Builder for the competency-agnostic general reference prompts.

These reference prompts are the retriever's LAST-RESORT fallback (Level 6):
loaded only when the 5-level fallback ladder returns ZERO references — i.e.
a brand-new combo with no curated or sibling prompt anywhere.

Their job is NOT to be a perfect tech-specific prompt. It is to give the
prompt-generator agent a structurally-correct skeleton to copy — most
importantly the CANONICAL output JSON schema (``name`` / ``question`` /
``code_files`` / ``answer`` / ...). Without this, bootstrap-mode generations
invent their own key names (``task_title`` / ``files`` / ``context``) and the
downstream multiagent.py reads every field as empty, producing a hollow task.
That was the PHP+Laravel failure (2026-05-15 validation run, finding F10).

Run ``python -m task_generation_prompts._general_reference._build_general_reference``
to (re)generate the four ``general_<level>_prompt.py`` files in this folder.
"""

from __future__ import annotations

from pathlib import Path

OUT_DIR = Path(__file__).parent

# Per-level calibration — the ONLY thing that differs between the four files.
LEVELS = {
    "BEGINNER": {
        "yoe": "0-1 years",
        "minutes": "20-30",
        "complexity": "a single isolated concept — a syntax fix, a small bug, "
                      "or one simple function",
        "concepts": "one core concept only: basic syntax, simple control flow, "
                    "a single function, or a one-line bug fix",
        "forbidden": "async/await, design patterns, performance optimization, "
                     "multi-file architecture, testing frameworks",
    },
    "BASIC": {
        "yoe": "1-2 years",
        "minutes": "30-45",
        "complexity": "a well-scoped feature or bug fix combining 2-3 concepts",
        "concepts": "2-3 concepts: functions and modules, basic OOP, structured "
                    "error handling, standard-library data structures, simple tests",
        "forbidden": "system design, microservices, advanced concurrency, "
                     "security hardening, complex caching or partitioning",
    },
    "INTERMEDIATE": {
        "yoe": "3-5 years",
        "minutes": "45-60",
        "complexity": "a multi-concept task requiring design judgement, "
                      "refactoring, and correctness reasoning",
        "concepts": "4-5 concepts: optimization, architecture, proper testing, "
                    "error handling, performance tuning, separation of concerns",
        "forbidden": "full distributed-systems design, multi-team architecture, "
                     "anything that cannot be completed solo within the time box",
    },
    "ADVANCED": {
        "yoe": "5+ years",
        "minutes": "60-90",
        "complexity": "an open-ended design-and-build task with real trade-offs",
        "concepts": "system design, scalability, advanced concurrency, deep "
                    "architecture, observability, and failure-mode reasoning",
        "forbidden": "trivia, pure theory, anything that does not produce "
                     "running, reviewable code",
    },
}

# The template. Double braces ``{{`` ``}}`` are literal braces in the OUTPUT
# file (they survive .format() here AND must survive str.format() downstream).
# Single-brace ``{level}`` etc. are substituted by THIS builder only.
_FILE_TEMPLATE = '''\
"""General reference prompt — {level} — competency-agnostic.

AUTO-GENERATED by _build_general_reference.py. Do not edit by hand; edit the
builder and re-run it.

This file is the retriever's Level-6 last-resort reference: used only when no
curated or sibling prompt exists for a combo. It demonstrates the canonical
3-section structure and — critically — the canonical output JSON schema.
"""

PROMPT_GENERAL_{level}_CONTEXT = """
Let me provide you with some context about the company and role:

Company Context:
{{organization_background}}

Roles and Responsibilities:
{{role_context}}

Based on this information, summarize what you understand about the company and
the role requirements before we proceed.
"""

PROMPT_GENERAL_{level}_INPUT_AND_ASK = """
Now that you understand the company context, here are the inputs for generating
a {level} assessment task.

INPUT COMPETENCIES:
{{competencies}}

INPUT ROLE CONTEXT:
{{role_context}}

INPUT REAL-WORLD SCENARIOS FOR TASK INSPIRATION:
{{real_world_task_scenarios}}

CRITICAL TASK GENERATION REQUIREMENTS:
- Draw inspiration from ONE of the real-world scenarios above.
- The task must be {complexity}.
- It must be completable within {minutes} minutes by a candidate with {yoe}
  of experience.
- Pick a different scenario each time for variety.

Briefly confirm your understanding:
1. What will the task be about (domain, context, problem)?
2. What will the candidate build or fix, and how does it match {level} level?
"""

PROMPT_GENERAL_{level}_INSTRUCTIONS = """
# {level} Task Requirements (General Reference)

## GOAL
As a technical architect, generate a complete assessment task — description,
starter code files, README — that tests a candidate at {level} proficiency
({yoe} experience). The task must be {complexity}.

## INSTRUCTIONS
- The task asks the candidate to implement a feature or fix a bug in existing
  starter code. Focus on {concepts}.
- Generate enough starter code to give a clear starting point WITHOUT giving
  away the solution.
- The starter code MUST run cleanly (zero syntax/runtime errors) and must
  implement exactly the "Current Implementation" buggy/incomplete state.
- Do NOT include the solution, TODO comments, or hints in the starter code.
- Avoid: {forbidden}.
- Time box: each task MUST be completable within {{minutes_range}} minutes.
- Task name: short, under 50 characters, kebab-case.
- For executable code, always invoke interpreters by their explicit name
  (e.g. `python3`, never bare `python`).

## REQUIRED OUTPUT JSON STRUCTURE (CANONICAL — use these EXACT key names)
The downstream system reads these exact top-level keys. Do NOT rename them to
synonyms (no "task_title", no "files", no "context") — synonyms produce a
hollow, unusable task.

{{{{
  "name": "task-name-in-kebab-case",
  "question": "Structured task description. MUST include: (1) Current Implementation — the exact buggy/incomplete state the starter code implements; (2) Required Changes — the specific fixes or features the candidate must implement.",
  "code_files": {{{{
    "README.md": "Candidate-facing README (structure below)",
    ".gitignore": "Standard exclusions for the task's language/stack",
    "main entry file": "The runnable entry point",
    "additional files": "Other modules/helpers as needed"
  }}}},
  "outcomes": "Bullet list — expected results after completion.",
  "short_overview": "Bullet list — (1) business context, (2) implementation goal, (3) expected outcome.",
  "pre_requisites": "Bullet list — tools, environment, and knowledge required.",
  "answer": "High-level solution approach (evaluator-facing; never shown to the candidate).",
  "hints": "Single line nudging the focus area WITHOUT revealing the answer.",
  "definitions": {{{{
    "term_1": "definition_1",
    "term_2": "definition_2"
  }}}}
}}}}

## README.md STRUCTURE
The "README.md" entry inside code_files MUST contain these sections, each fully
populated with specific, task-relevant content (no placeholders):
- Task Overview      — 2-3 sentences on the business scenario and current state
- Objectives         — clear, measurable goals used to verify completion
- How to Verify      — concrete checkpoints and observable outcomes
- Helpful Tips       — guidance that aids discovery without revealing solutions

## CRITICAL REMINDERS
1. Environment runs perfectly out of the box; the candidate fixes the TASK,
   not the environment.
2. Starter code is runnable but does NOT contain the core solution.
3. Starter code perfectly matches the "Current Implementation".
4. No solution-revealing comments.
5. Completable within {{minutes_range}} minutes.
6. Output JSON uses the CANONICAL key names above — this is non-negotiable.
"""

PROMPT_REGISTRY = {{
    "General Reference ({level})": [
        PROMPT_GENERAL_{level}_CONTEXT,
        PROMPT_GENERAL_{level}_INPUT_AND_ASK,
        PROMPT_GENERAL_{level}_INSTRUCTIONS,
    ]
}}
'''


def build() -> list[Path]:
    written: list[Path] = []
    for level, cfg in LEVELS.items():
        content = _FILE_TEMPLATE.format(level=level, **cfg)
        out_path = OUT_DIR / f"general_{level.lower()}_prompt.py"
        out_path.write_text(content, encoding="utf-8")
        written.append(out_path)
    return written


if __name__ == "__main__":
    paths = build()
    for p in paths:
        print(f"wrote {p}")
