"""General reference prompt — BASIC — competency-agnostic.

AUTO-GENERATED by _build_general_reference.py. Do not edit by hand; edit the
builder and re-run it.

This file is the retriever's Level-6 last-resort reference: used only when no
curated or sibling prompt exists for a combo. It demonstrates the canonical
3-section structure and — critically — the canonical output JSON schema.
"""

PROMPT_GENERAL_BASIC_CONTEXT = """
Let me provide you with some context about the company and role:

Company Context:
{organization_background}

Roles and Responsibilities:
{role_context}

Based on this information, summarize what you understand about the company and
the role requirements before we proceed.
"""

PROMPT_GENERAL_BASIC_INPUT_AND_ASK = """
Now that you understand the company context, here are the inputs for generating
a BASIC assessment task.

INPUT COMPETENCIES:
{competencies}

INPUT ROLE CONTEXT:
{role_context}

INPUT REAL-WORLD SCENARIOS FOR TASK INSPIRATION:
{real_world_task_scenarios}

CRITICAL TASK GENERATION REQUIREMENTS:
- Draw inspiration from ONE of the real-world scenarios above.
- The task must be a well-scoped feature or bug fix combining 2-3 concepts.
- It must be completable within 30-45 minutes by a candidate with 1-2 years
  of experience.
- Pick a different scenario each time for variety.

Briefly confirm your understanding:
1. What will the task be about (domain, context, problem)?
2. What will the candidate build or fix, and how does it match BASIC level?
"""

PROMPT_GENERAL_BASIC_INSTRUCTIONS = """
# BASIC Task Requirements (General Reference)

## GOAL
As a technical architect, generate a complete assessment task — description,
starter code files, README — that tests a candidate at BASIC proficiency
(1-2 years experience). The task must be a well-scoped feature or bug fix combining 2-3 concepts.

## INSTRUCTIONS
- The task asks the candidate to implement a feature or fix a bug in existing
  starter code. Focus on 2-3 concepts: functions and modules, basic OOP, structured error handling, standard-library data structures, simple tests.
- Generate enough starter code to give a clear starting point WITHOUT giving
  away the solution.
- The starter code MUST run cleanly (zero syntax/runtime errors) and must
  implement exactly the "Current Implementation" buggy/incomplete state.
- Do NOT include the solution, TODO comments, or hints in the starter code.
- Avoid: system design, microservices, advanced concurrency, security hardening, complex caching or partitioning.
- Time box: each task MUST be completable within {minutes_range} minutes.
- Task name: short, under 50 characters, kebab-case.
- For executable code, always invoke interpreters by their explicit name
  (e.g. `python3`, never bare `python`).

## REQUIRED OUTPUT JSON STRUCTURE (CANONICAL — use these EXACT key names)
The downstream system reads these exact top-level keys. Do NOT rename them to
synonyms (no "task_title", no "files", no "context") — synonyms produce a
hollow, unusable task.

{{
  "name": "task-name-in-kebab-case",
  "question": "Structured task description. MUST include: (1) Current Implementation — the exact buggy/incomplete state the starter code implements; (2) Required Changes — the specific fixes or features the candidate must implement.",
  "code_files": {{
    "README.md": "Candidate-facing README (structure below)",
    ".gitignore": "Standard exclusions for the task's language/stack",
    "main entry file": "The runnable entry point",
    "additional files": "Other modules/helpers as needed"
  }},
  "outcomes": "Bullet list — expected results after completion.",
  "short_overview": "Bullet list — (1) business context, (2) implementation goal, (3) expected outcome.",
  "pre_requisites": "Bullet list — tools, environment, and knowledge required.",
  "answer": "High-level solution approach (evaluator-facing; never shown to the candidate).",
  "hints": "Single line nudging the focus area WITHOUT revealing the answer.",
  "definitions": {{
    "term_1": "definition_1",
    "term_2": "definition_2"
  }}
}}

## README.md STRUCTURE
The "README.md" entry inside code_files MUST contain these sections, each fully
populated with specific, task-relevant content (no placeholders):
- Task Overview      — 2-3 sentences on the business scenario and current state
- Objectives         — clear, measurable goals used to verify completion
- How to Verify      — concrete checkpoints and observable outcomes
- Helpful Tips       — guidance that aids discovery without revealing solutions

## CRITICAL REMINDERS
1. Environment runs perfectly out of the box; the candidate fixes the TASK,
   not the environment.
2. Starter code is runnable but does NOT contain the core solution.
3. Starter code perfectly matches the "Current Implementation".
4. No solution-revealing comments.
5. Completable within {minutes_range} minutes.
6. Output JSON uses the CANONICAL key names above — this is non-negotiable.
"""

PROMPT_REGISTRY = {
    "General Reference (BASIC)": [
        PROMPT_GENERAL_BASIC_CONTEXT,
        PROMPT_GENERAL_BASIC_INPUT_AND_ASK,
        PROMPT_GENERAL_BASIC_INSTRUCTIONS,
    ]
}
